# Generated by Django 3.2.9 on 2021-11-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211110_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
