# Generated by Django 3.2.9 on 2021-11-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_student_matric_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.room'),
        ),
        migrations.AddField(
            model_name='student',
            name='room_allotted',
            field=models.BooleanField(default=False),
        ),
    ]
