# Generated by Django 3.2.9 on 2021-11-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211110_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warden',
            old_name='name',
            new_name='address',
        ),
        migrations.AddField(
            model_name='warden',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='qualification',
            field=models.CharField(choices=[('BSc', 'BSc'), ('HND', 'HND'), ('ND', 'ND')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='title',
            field=models.CharField(choices=[('mr', 'Mr'), ('miss', 'Miss'), ('mrs', 'Mrs')], max_length=4, null=True),
        ),
    ]
