# Generated by Django 3.2.9 on 2021-11-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.faculty'),
        ),
    ]
