# Generated by Django 3.2.9 on 2021-11-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_allocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.hostel'),
        ),
    ]
