# Generated by Django 3.2.9 on 2021-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_student_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6, null=True),
        ),
    ]
