# Generated by Django 3.2.9 on 2021-11-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_hostel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='repair',
            new_name='facilities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='caretaker',
        ),
        migrations.RemoveField(
            model_name='room',
            name='no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matric_no',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='receipt_no',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hostel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.hostel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L'), ('500L', '500L')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.room'),
        ),
        migrations.AddField(
            model_name='student',
            name='bed_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bed'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.course'),
        ),
    ]
