# Generated by Django 3.2.9 on 2021-11-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20211112_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_registration',
            new_name='date_of_created',
        ),
        migrations.RemoveField(
            model_name='allocate',
            name='room',
        ),
        migrations.RemoveField(
            model_name='allocate',
            name='student',
        ),
        migrations.AddField(
            model_name='bed',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='warden',
            name='hostel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.hostel'),
        ),
    ]
