# Generated by Django 3.2.9 on 2021-11-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20211112_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='room',
            new_name='room_no',
        ),
    ]
