# Generated by Django 3.2.9 on 2021-11-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20211112_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
        ),
    ]
