# Generated by Django 3.2.9 on 2021-11-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
        ),
    ]
