# Generated by Django 3.2.9 on 2021-11-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_bed_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
        ),
    ]
