# Generated by Django 3.2.9 on 2021-11-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_bed_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='receipt_no',
            field=models.CharField(help_text='Ensure you enter a valid receipt number.', max_length=200, null=True, unique=True),
        ),
    ]
