# Generated by Django 3.2.9 on 2021-11-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20211113_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
        ),
    ]
