# Generated by Django 3.2.9 on 2021-11-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_bed_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='room',
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ManyToManyField(null=True, to='account.Room'),
        ),
    ]
