# Generated by Django 3.2.9 on 2021-11-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20211113_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='room',
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
        ),
    ]
