# Generated by Django 3.2.9 on 2021-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20211113_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
