# Generated by Django 3.2.9 on 2021-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_room_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ManyToManyField(null=True, to='account.Hostel'),
        ),
    ]
