# Generated by Django 3.2.9 on 2021-11-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20211113_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hostel'),
        ),
    ]
